version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: sharedsaver_db
    environment:
      POSTGRES_DB: sharedsaver_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sharedsaver_network

  # Redis (for caching and background tasks)
  redis:
    image: redis:7-alpine
    container_name: sharedsaver_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sharedsaver_network

  # Django Application (optional - for production)
  web:
    build: .
    container_name: sharedsaver_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=sharedsaver_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - sharedsaver_network

volumes:
  postgres_data:
  redis_data:

networks:
  sharedsaver_network:
    driver: bridge 