# Generated by Django 5.2.4 on 2025-07-22 06:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('can_contribute', models.BooleanField(default=True)),
                ('can_borrow', models.BooleanField(default=True)),
                ('can_invite', models.BooleanField(default=False)),
                ('can_manage', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'account_memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('account_type', models.CharField(choices=[('family', 'Family Account'), ('friends', 'Friends Account'), ('business', 'Business Account')], default='family', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('allow_loans', models.BooleanField(default=True)),
                ('max_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('min_contribution', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shared_accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
