# Generated by Django 5.2.4 on 2025-07-22 06:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('repaid', 'Repaid'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('term_months', models.PositiveIntegerField(default=12)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('repaid_at', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='accounts.sharedaccount')),
            ],
            options={
                'db_table': 'loans',
                'ordering': ['-created_at'],
            },
        ),
    ]
